#
# $Id: Makefile,v 1.3 2012/11/01 21:36:57 roselynl Exp $
#

SUBDIR = \
	bigdecimal \
	syslog \
	objspace \
	fiber \
	coverage \
	zlib \
	json \
	date \
	pty \
	nkf \
	pathname \
	stringio \
	ripper \
	fcntl \
	io \
	syck \
	iconv \
	etc \
	enc \
	psych \
	strscan \
	openssl \
	digest \
	socket \
	date

.include <bsd.subdir.mk>
