#
# $Id$
#

SUBDIR = \
	bigdecimal \
	continuation \
	coverage \
	date \
	dbm \
	digest \
	dl \
	enc \
	etc \
	fcntl \
	fiber \
	io \
	json \
	libxml \
	mathn \
	nkf \
	objspace \
	openssl \
	pathname \
	psych \
	pty \
	racc \
	readline \
	ripper \
	sdbm \
	socket \
	stringio \
	strscan \
	syck \
	syslog \
	zlib

#	curses \

.include <bsd.subdir.mk>

