#
# $Id: Makefile,v 1.3 2012/11/01 21:36:57 roselynl Exp $
#

SUBDIR = \
  bigdecimal \
  continuation \
  coverage \
  date \
  dbm \
  digest \
  dl \
  enc \
  etc \
  fcntl \
  fiber \
  iconv \
  io \
  json \
  libxml \
  mathn \
  nkf \
  objspace \
  openssl \
  pathname \
  psych \
  pty \
  racc \
  readline \
  ripper \
  sdbm \
  socket \
  stringio \
  strscan \
  syck \
  syslog \
  zlib

.include <bsd.subdir.mk>
