#
# $Id: Makefile,v 1.1.1.1 2012/10/30 16:42:08 roselynl Exp $
#

.include "../Makefile.inc"

LIB = stringio
SHLIB_NAME = ${LIB}.so

.PATH: ${RUBY_EXT_DIR}/stringio
SRCS = stringio.c

.include <bsd.lib.mk>

