#
# $Id$
#

SUBDIR = \
	big5 \
	cp949 \
	emacs_mule \
	encdb \
	euc_jp \
	euc_kr \
	euc_tw \
	gb18030 \
	gb2312 \
	gbk \
	iso_8859_1 \
	iso_8859_10 \
	iso_8859_11 \
	iso_8859_13 \
	iso_8859_14 \
	iso_8859_15 \
	iso_8859_16 \
	iso_8859_2 \
	iso_8859_3 \
	iso_8859_4 \
	iso_8859_5 \
	iso_8859_6 \
	iso_8859_7 \
	iso_8859_8 \
	iso_8859_9 \
	koi8_r \
	koi8_u \
	shift_jis \
	utf_16be \
	utf_16le \
	utf_32be \
	utf_32le \
	windows_1251

.include <bsd.subdir.mk>

