#
# $Id$
#
# Copyright (c) 2006-2008, Juniper Networks, Inc.
# All rights reserved.
#

SUBDIR = \
  libcrypto \
  libiconv \
  libssl \
  libxml2 \
  libyaml \
  zlib \
  ncurses \
  libedit \
  ruby \
  gems

.include <bsd.subdir.mk>
